pluginManagement {
    def props = new java.util.Properties()
    file('gradle.properties').withInputStream { props.load(it) }

    resolutionStrategy {
        eachPlugin {
            if (requested.id.id == 'fabric-loom') {
                useModule("net.fabricmc:fabric-loom:${props.getProperty('loom_version')}")
            }
        }
    }

    repositories {
        maven { name = 'Fabric'; url = 'https://maven.fabricmc.net/' }
        gradlePluginPortal()
        mavenCentral()
    }
}

rootProject.name = 'SmartMoving-Fabric'
